### ISSUE TITLE
European Style representation

### ISSUE THREAD

**Issue by ees4all** [mph-/lcapy#103]
According to the European Style the representation of voltage in loads like Resistors by means of arrows go from + to - .
Therefore 
It seems to be a problem with Circuitikz:

[https://tex.stackexchange.com/questions/298538/european-convention-of-voltage-in-circuitikz](url)
and
[https://tex.stackexchange.com/questions/37182/voltage-sign-convention-european-vs-american-in-circuitikz](url)

 how can I use Lcapy but with the correct arrows from + to - ?

Here and Code Example which is sketch uncorrectly the voltage arrows:
``
``sch='''
Vq 1 0 ; down=2, i={i_{V_{q}}},
W 1 2 ;  right, size=1
R1 2 3 ; down, v={v_{R1}}
R2 3 4; down, v={v_{R2}}
W 3 5; right
P1 5 6; down,v=U_{out}
W 4 6; right
W 4 0; left
`
#Demonstrate that we can write the description to a file 
filevoltagedivider="voltageDivider.sch"
with open(filevoltagedivider, "w") as text_file: # open the file for writing
    text_file.write(sch) # write the description to the file
# Description: Voltage Divider using lcapy
import matplotlib.pyplot as plt
import lcapy as lp # we need to import the lcapy library

#  and then create the circuit model from the (persisted) file    
cct = lp.Circuit(filevoltagedivider)
cct.draw(style='european', label_nodes='alpha') # draw the circuit where american style is used and the nodes aredue to alpha labelled with letters
!schtex voltageDivider.sch voltageDivider.png # export the schematic to a png file
`
``

thanks in advance

**Comment by mph-** [comment]
Have you tried adding at end
`; voltage_dir=EF`

By default `voltage_dir` is `RP`.
