### ISSUE TITLE
state space issues when using without sources

### ISSUE THREAD

**Issue by floke9** [mph-/lcapy#105]
I have spotted an issue using state_equations() method on a discrete state space object when there are no sources. As far I have seen that the calculation of A*x+B*u for the discrete variant does not check for empty B or u matrix.

Example Code:

`from lcapy import Circuit

c = Circuit("""
R1 1 2;
R2 1 0;
C1 2 0;
""")

ss = c.ss
ssd = c.ss.discretize()

ss.state_equations()
ss.output_equations()
ssd.state_equations()
ssd.output_equations()`

**Comment by mph-** [comment]
Thanks for pointing this out.  I fixed this for the CT case some time ago but stupidly forgot the DT case.

Note, SymPy will issue some deprecation warnings that you can ignore.  Unfortunately, soon I won't be able to store Lcapy objects in a SymPy Matrix and will have to implement my own Matrix class...
