### ISSUE TITLE
Numerical Issue Bode plot: Non-Ideal inverting integrator

### ISSUE THREAD

**Issue by davidparent** [mph-/lcapy#111]
It seems that the smallest magnitude of a bode plot (I tried 1/(s+1) and − 1000000/(s(s+1000001))
is around 140dB
​

Here is my co-lab file:
https://colab.research.google.com/drive/1NxAeozFvhL9a9gzLShMODxm5u720umVN?usp=sharing

**Comment by davidparent** [comment]
It happens in the docs too.:
from matplotlib.pyplot import savefig
from lcapy import *

H = 1 / (s**2 + 20*s + 10000)

H.bode_plot((1, 1000))

No matter how high the frequency, it is limited to a minium of -120dB.

**Comment by mph-** [comment]
Try

`H.bode_plot((1, 1000), dbmin=-140)`

**Comment by davidparent** [comment]
This worked great.  Sorry for the delay
