### ISSUE TITLE
MNA equations example does not run

### ISSUE THREAD

**Issue by timchinowsky** [mph-/lcapy#112]
`lcapy` looks great, considering having students in the lab class I am currently teaching use it to gain insights into simulation.  Trying to derive and display the MNA equations as shown in https://lcapy.readthedocs.io/en/latest/circuits.html#networks-and-netlists, not having any luck, seems like the technique has changed.  Attaching a zipped Jupyter notebook showing my attempts.  New to `lcapy`, am I missing something simple?  Thanks!

[mna_equations.zip](https://github.com/mph-/lcapy/files/13210310/mna_equations.zip)

**Comment by mph-** [comment]
Thanks for letting me know.  It seems like I inadvertently removed it when cleaning up some code!   Anyway, I have pushed a patch to restore it.

**Comment by timchinowsky** [comment]
Wonderful, thanks!
