### ISSUE TITLE
Rendering schematic in not showing in notebook

### ISSUE THREAD

**Issue by GProtoZeroW** [mph-/lcapy#15]
I was in the past able to display the schematics fine in the notebook but recently I just get broken image link images. I am on mint with a full tex install, jupyter version 4.4.0, lcapy 0.28.0

**Comment by mph-** [comment]
Have you tried with the latest code?

There is a problem with new versions of ImageMagick when converting a pdf to png with the convert program.   By default this conversion is disabled unless allowed in a system configuration file, see [here](https://stackoverflow.com/questions/52998331/imagemagick-security-policy-pdf-blocking-conversion) As a workaround I try using pdftoppm if convert fails.
