### ISSUE TITLE
state space model is different when voltage source is a number or not

### ISSUE THREAD

**Issue by wkjung** [mph-/lcapy#151]
The circuit below shows different state equations when `V` is assigned a value or not.

<img width="461" alt="image" src="https://github.com/user-attachments/assets/fd6c5aaa-082b-4d1e-981f-35b6ee3fe993">

```py
model = lcapy.Circuit("""
I1 1 0 {i1(t)}; left
R 1 2 3; right=2
C 1 0 5; down
V 2 0; down
;autoground=ground """)
ss = model.state_space(node_voltages=[1], branch_currents=[])
display(ss.state_equations())
```
Output:
<img width="298" alt="image" src="https://github.com/user-attachments/assets/03d46549-21b3-4767-bc27-9c6aab14825d">

When V is assigned:
```py
model = lcapy.Circuit("""
I1 1 0 {i1(t)}; left
R 1 2 3; right=2
C 1 0 5; down
V 2 0 7; down
;autoground=ground """)
ss = model.state_space(node_voltages=[1], branch_currents=[])
display(ss.state_equations())
```
Output (you can see that the `V` value, 7, is ignored now):
<img width="281" alt="image" src="https://github.com/user-attachments/assets/d6d335d6-dd76-409d-a0db-6e6026e7d142">

Why is this? Seems like the upper one is right (following KCL), then how can I get the right result when I want to assign a value to `V` _before_ generating state space model?

**Comment by mph-** [comment]
Yes, that's not correct.  Thanks for letting me know.  I'll have a think...

**Comment by mph-** [comment]
I have pushed a fix for this problem.

Note, I am thinking of changing the current source polarity to match SPICE.  I have a branch that accomplishes this but am not sure how to make the switch graceful.
