### ISSUE TITLE
Ground symbol?

### ISSUE THREAD

**Issue by Cabalist** [mph-/lcapy#16]
This is more of cosmetic question than a functional one.

I'm trying to model a voltage divider that looks like this:
<img src="https://user-images.githubusercontent.com/828557/53927177-d2c64200-403a-11e9-9a3e-97b5c9a616af.jpg" width=240>

I can't seem to find an immediate way to draw the ground symbol with lcapy.  

I'm aware of the Voltage divider in the intro to schematics here:http://lcapy.elec.canterbury.ac.nz/schematics.html#introduction but I'm curious if this other cosmetic variety is possible.

Here is an example in circuitikz of what I'm trying to do as well:
```latex
            \begin{circuitikz}
                \draw (0,0)
                to[short] (2,0)
                to[R=$R_1$] (2, -2)
                to[R=$R_2$] (2,-4)
                to[short] node[ground] {} (2, -4);
                \draw (2,-2)
                to[short] (4, -2)
                to[R=$R_{load}$] (4, -4)
                to[short] node[ground] {} (4, -4);
            \end{circuitikz}
```

**Comment by mph-** [comment]
Yes, you can do this with the ground attribute for a wire.  For example,

`W 1 2; down, ground`

I have recently added support for other ground symbols and have added them to the docs.  However, I'm in the process of a radical overhaul for schematic drawing so will not push them out yet.
