### ISSUE TITLE
Op-Amps Unsupported?

### ISSUE THREAD

**Issue by firebolt55439** [mph-/lcapy#17]
None of the op-amp examples work with the newest version of `lcapy` since the `Opamp` class is no longer exposed for imports. Is op-amp analysis supported for simple op-amp networks? 

Not looking for anything too fancy. I keep getting "MNA A matrix not invertible" errors when attempting to analyze voltage gain across simple op-amp configurations.

**Comment by mph-** [comment]
Hello

Opamps should be working.  There is an example in the `doc/examples/notebooks/opamp-noninverting-amplifier1.ipynb` notebook.

The matrix not invertible error usually occurs when you do not have a DC path for a node to ground.

Could you post a simplified testcase please?

Michael.

**Comment by firebolt55439** [comment]
Ah I see, I was looking at the old examples, which is why I couldn't get anything to work. No wonder. Thanks for your help :)

**Comment by mph-** [comment]
Ah, which old examples did you find?   If they are in the docs, I'll remove or update them.

**Comment by firebolt55439** [comment]
Pretty much all the ones in here: [https://github.com/mph-/lcapy/tree/master/demo/notebooks](https://github.com/mph-/lcapy/tree/master/demo/notebooks)
