### ISSUE TITLE
Zero node on DC voltage source causes initial capacitor value to be ignored

### ISSUE THREAD

**Issue by draustin** [mph-/lcapy#23]
Hi and thanks for lcapy. I'm using it for transient analysis of a photoreceiver circuit and it seems a great tool.
I've encountered behavior which is confusing me and might be a bug. I've written it up in the attached notebook.
[lcapy issue.pdf](https://github.com/mph-/lcapy/files/3740383/lcapy.issue.pdf)

**Comment by mph-** [comment]
Thanks for the detailed analysis.  I've added a fix for this case.  Indeed it only happens when a capacitor is connected to ground for an initial value problem.  Coincidentally, all week I've been meaning to add more unit tests for IVPs.
