### ISSUE TITLE
.dc().equations() not behaving....

### ISSUE THREAD

**Issue by frohro** [mph-/lcapy#26]
I was looking at the .equations() option, and was following the example [here](http://lcapy.elec.canterbury.ac.nz/tutorial.html#modified-nodal-analysis).   See below:

`from lcapy import Circuit

a = Circuit("""
... V1 1 0 {10 + v(t)}; down
... R1 1 2; right
... L1 2 3; right=1.5, i={i_L}
... R2 3 0_3; down=1.5, i={i_{R2}}, v={v_{R2}}
... W 0 0_3; right
... W 3 3_a; right
... C1 3_a 0_4; down, i={i_C}, v={v_C}
... W 0_3 0_4; right""")
a.draw(label_nodes=True)
a.dc()
a.dc().equations()`

The result I get is:

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-16-c36b74b9980b> in <module>
     12 a.draw(label_nodes=True)
     13 a.dc()
---> 14 a.dc().equations()

~/anaconda3/lib/python3.7/site-packages/lcapy-0.38.2-py3.7.egg/lcapy/mna.py in equations(self, inverse)
    257                                evaluate=False))
    258 
--> 259         return expr(sym.Eq(self.X, sym.MatMul(sym.Pow(self._A, -1), self._Z),
    260                                evaluate=False))                           

~/anaconda3/lib/python3.7/site-packages/lcapy-0.38.2-py3.7.egg/lcapy/mna.py in X(self)
    226         self._analyse()
    227 
--> 228         V = [self.Vname('Vn%s' % node) for node in self.node_list[1:]]
    229         I = [self.Iname('I%s' % branch) for branch in self.unknown_branch_currents]
    230         return Vector(V + I)

~/anaconda3/lib/python3.7/site-packages/lcapy-0.38.2-py3.7.egg/lcapy/mna.py in <listcomp>(.0)
    226         self._analyse()
    227 
--> 228         V = [self.Vname('Vn%s' % node) for node in self.node_list[1:]]
    229         I = [self.Iname('I%s' % branch) for branch in self.unknown_branch_currents]
    230         return Vector(V + I)

~/anaconda3/lib/python3.7/site-packages/lcapy-0.38.2-py3.7.egg/lcapy/netlist.py in Vname(self, name)
   1228 
   1229     def Vname(self, name):
-> 1230         return Vname(name, self.kind)
   1231 
   1232     def Iname(self, name):

~/anaconda3/lib/python3.7/site-packages/lcapy-0.38.2-py3.7.egg/lcapy/voltage.py in Vname(name, kind, cache)
    104     elif kind == 't':
    105         return Vt(name + '(t)')
--> 106     elif kind in (omegasym, omega, 'ac'):
    107         return Vphasor(name + '(omega)')
    108     # Not caching is a hack to avoid conflicts of Vn1 with Vn1(s) etc.

NameError: name 'omegasym' is not defined
​
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-14-716e42ffcfcd> in <module>
----> 1 a.dc().equations()

~/anaconda3/lib/python3.7/site-packages/lcapy-0.38.2-py3.7.egg/lcapy/mna.py in equations(self, inverse)
    257                                evaluate=False))
    258 
--> 259         return expr(sym.Eq(self.X, sym.MatMul(sym.Pow(self._A, -1), self._Z),
    260                                evaluate=False))                           

~/anaconda3/lib/python3.7/site-packages/lcapy-0.38.2-py3.7.egg/lcapy/mna.py in X(self)
    226         self._analyse()
    227 
--> 228         V = [self.Vname('Vn%s' % node) for node in self.node_list[1:]]
    229         I = [self.Iname('I%s' % branch) for branch in self.unknown_branch_currents]
    230         return Vector(V + I)

~/anaconda3/lib/python3.7/site-packages/lcapy-0.38.2-py3.7.egg/lcapy/mna.py in <listcomp>(.0)
    226         self._analyse()
    227 
--> 228         V = [self.Vname('Vn%s' % node) for node in self.node_list[1:]]
    229         I = [self.Iname('I%s' % branch) for branch in self.unknown_branch_currents]
    230         return Vector(V + I)

~/anaconda3/lib/python3.7/site-packages/lcapy-0.38.2-py3.7.egg/lcapy/netlist.py in Vname(self, name)
   1228 
   1229     def Vname(self, name):
-> 1230         return Vname(name, self.kind)
   1231 
   1232     def Iname(self, name):

~/anaconda3/lib/python3.7/site-packages/lcapy-0.38.2-py3.7.egg/lcapy/voltage.py in Vname(name, kind, cache)
    104     elif kind == 't':
    105         return Vt(name + '(t)')
--> 106     elif kind in (omegasym, omega, 'ac'):
    107         return Vphasor(name + '(omega)')
    108     # Not caching is a hack to avoid conflicts of Vn1 with Vn1(s) etc.

NameError: name 'omegasym' is not defined

Any suggestions?

Thanks,

Rob

**Comment by mph-** [comment]
Hi Rob

I've pushed a patch for this.

Michael
