### ISSUE TITLE
.Thevenin and Norton Circuits of Circuits with Dependent Sources?

### ISSUE THREAD

**Issue by frohro** [mph-/lcapy#28]
I'm wondering if I have a misunderstanding about entering current dependent voltage sources, and other dependent sources.  The problem is with Thevenin/Norton circuits.  I made an example which I expected to be equivalent to four Ohms.
`cct1 = Circuit('''
H1 1 0 H1 -4; down=1.5, l=4i, i=i
''')
cct1.draw(label_nodes=True)
cct1.norton(1, 0)
cct1.thevenin(1, 0)`
I get an error.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/lcapy-0.38.2-py3.7.egg/lcapy/mna.py in _branch_index(self, cpt_name)
     74         try:
---> 75             index = self.unknown_branch_currents.index(cpt_name)
     76             return index

ValueError: '0' is not in list

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-34-96ded85dd8af> in <module>
      3 ''')
      4 cct1.draw(label_nodes=True)
----> 5 cct1.norton(1, 0)
      6 #cct1.thevenin(1, 0)

~/anaconda3/lib/python3.7/site-packages/lcapy-0.38.2-py3.7.egg/lcapy/netlist.py in norton(self, Np, Nm)
    617         Np, Nm = self._parse_node_args(Np, Nm)
    618         Isc = self.Isc(Np, Nm)
--> 619         Ysc = self.admittance(Np, Nm)
    620 
    621         # Convert to time-domain to handle arbitrary sources.  Either

~/anaconda3/lib/python3.7/site-packages/lcapy-0.38.2-py3.7.egg/lcapy/netlist.py in admittance(self, Np, Nm)
    640         # measure current.
    641         new._add('Vin_ %s %s {DiracDelta(t)}' % (Np, Nm))
--> 642         If = new.Vin_.I
    643         new.remove('Vin_')
    644 

~/anaconda3/lib/python3.7/site-packages/lcapy-0.38.2-py3.7.egg/lcapy/mnacpts.py in I(self)
    269         for sources."""
    270 
--> 271         return self.cct.get_I(self.name)
    272 
    273     @property

~/anaconda3/lib/python3.7/site-packages/lcapy-0.38.2-py3.7.egg/lcapy/netlist.py in get_I(self, name)
   1375         result = Current()
   1376         for sub in self.sub.values():
-> 1377             I = sub.get_I(name)
   1378             result.add(I)
   1379         result = result.canonical()

~/anaconda3/lib/python3.7/site-packages/lcapy-0.38.2-py3.7.egg/lcapy/netlist.py in get_I(self, name)
   1475         """Current through component"""
   1476 
-> 1477         self._solve()
   1478         return self._Idict[name].canonical()
   1479 

~/anaconda3/lib/python3.7/site-packages/lcapy-0.38.2-py3.7.egg/lcapy/mna.py in _solve(self)
    132         if hasattr(self, '_Vdict'):
    133             return
--> 134         self._analyse()
    135 
    136         if '0' not in self.node_map:

~/anaconda3/lib/python3.7/site-packages/lcapy-0.38.2-py3.7.egg/lcapy/mna.py in _analyse(self)
    119         # Iterate over circuit elements and fill in matrices.
    120         for elt in self.elements.values():
--> 121             elt.stamp(self)
    122 
    123         # Augment the admittance matrix to form A matrix.

~/anaconda3/lib/python3.7/site-packages/lcapy-0.38.2-py3.7.egg/lcapy/mnacpts.py in stamp(self, cct)
    789             cct._C[m, n2] -= 1
    790 
--> 791         mc = cct._branch_index(self.args[0])
    792         G = cExpr(self.args[1]).expr
    793         cct._D[m, mc] -= G

~/anaconda3/lib/python3.7/site-packages/lcapy-0.38.2-py3.7.egg/lcapy/mna.py in _branch_index(self, cpt_name)
     76             return index
     77         except ValueError:
---> 78             raise ValueError('Unknown component name %s for branch current' % cpt_name)
     79 
     80     def _analyse(self):

ValueError: Unknown component name 0 for branch current

Did I do this right?  It was a test case for the following circuit, because this case didn't give me a believable answer.  I get 2.222 Ohms myself, but it comes out with $Z_TH =5$.
`cct5 = Circuit("""
P1 1 0; down=3
W 1 1_0; right=1.5
W 0 0_0; right=1.5
E1 1_0 2 2 0 3; down, l=3 v_{R1}
R1 2 0_0 5; down=1.5, v=v_{R1}
R2 2 3 2; right=1.5
W 0_0 0_1; right 1.5
G1 3 0_1 2 0 2; down=1.5, l=2 v_{R1}
""")
cct5.draw(label_nodes=True, draw_nodes='connections')
cct5.norton(1, 0)
cct5.thevenin(1,0)`

Does lcapy handle Thevenin and Norton circuits with dependent sources?  Or maybe I didn't enter them correctly.
Thanks,
Rob

**Comment by mph-** [comment]
That's a cunning circuit Rob.  Yes, you did everything correct.  I've pushed a small fix to handle it but while trying to write a test case I've found another bug!

Michael.
