### ISSUE TITLE
lcapy draw function not working

### ISSUE THREAD

**Issue by ammu980525** [mph-/lcapy#31]
I have been trying to execute the following code (an example from http://lcapy.elec.canterbury.ac.nz/overview.html#schematics) using jupyter notebook:

%matplotlib inline
from lcapy import R, C, L
((R(1) + L(2)) | C(3)).draw()

I have manually installed the relevant LaTex packages such as circuitikz, pdflatex in a locally created latex folder. Once I execute this code, I end up getting the following error:

RuntimeError: (%s is not installed', 'pdflatex')

Can you tell why the draw function is not working?

**Comment by mph-** [comment]
Hello, you have not properly installed pdflatex

If you run pdflatex from the command line you should get something like:

This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
**
