### ISSUE TITLE
ValueError: Cannot convert non-causal s-expression to jomega domain

### ISSUE THREAD

**Issue by Mvanti** [mph-/lcapy#32]
When I try examples like the one shown in RC-lpf1.ipynb notebook I get the following error message:ValueError: Cannot convert non-causal s-expression to jomega domain

**Comment by Mvanti** [comment]
I have lcapy running with sympy 1.6, python 3.8,  in windows 10.

**Comment by mph-** [comment]
Thanks for letting me know about this.  I've been meaning to overhaul the assumption handling.
