### ISSUE TITLE
Symbolic expression for output signal

### ISSUE THREAD

**Issue by SanchoPansa47** [mph-/lcapy#38]
Hello,

Is there a command to get a symbolic (in terms of s or jω) expression for a signal?
For example this completely linear circuit displays a non-linear behavior. I would like to see the symbolic expression for the output signal.

```
from lcapy import Circuit
import numpy as np
import matplotlib.pyplot as plt

cct = Circuit('''
... Vin 1 0 {sin(130e6*2*3.14159*t)}
... R1  1 0 1000
... C4  1 2 1.0e-5   0
... C2  2 3 39.0e-12 0
... C3  3 0 22.0e-12 0
... La  2 4 0.32e-6  0
... C1  4 0 3.0e-12  0''')

t = np.linspace(0, 2e-7, 1000)
Vinp = cct.Vin.v.evaluate(t)
Vout = cct.C1.v.evaluate(t)

plt.plot(t, Vinp, 'g', linewidth=2)
plt.plot(t, Vout, 'r', linewidth=2)
plt.grid(b=True, which='major', color='#666666', linestyle='-')
plt.minorticks_on()
plt.grid(b=True, which='minor', color='#999999', linestyle='-', alpha=0.2)
plt.show()
```
Here is waveform:

[[url=https://postimages.org/][img]https://i.postimg.cc/h4VbnZB2/python-simulation-nonlinear-behavior.jpg[/img][/url]](url)

**Comment by mph-** [comment]
Have a look at http://lcapy.elec.canterbury.ac.nz/expressions.html#voltages-and-currents

BTW, your circuit is LTI.
