### ISSUE TITLE
Mirroring transistors does not work

### ISSUE THREAD

**Issue by fakuivan** [mph-/lcapy#40]
Mirroring transistors on ``lcapy (0.63), python 3.8.0`` causes them to swap the inputs but the symbol stays the same:

![image](https://user-images.githubusercontent.com/15100012/99067847-2916b280-258a-11eb-8d08-ed64fa7f5343.png)

This is on a blank jupyter notebook with only that code and ``import lcapy`` on the top.

**Comment by mph-** [comment]
Thanks for letting me know.  I've pushed a patch for this.  You will need to use the invert attribute to flip horizontally.

**Comment by fakuivan** [comment]
Thanks for the reply! I tried using the ``invert`` attribute but it errored out telling me the component cannot be flipped.

**Comment by mph-** [comment]
Hello, did you install from git?  If so, what does the following give? 
 
  `from lcapy import show_version;   show_version()`

I'm going to generate a new pip release later today...

**Comment by fakuivan** [comment]
I've installed lcapy from pip, running from wsl1. Here's the version info:

```text
fakui@DESKTOP-TN8UDAO:~$ python3.8 -c 'from lcapy import show_version; show_version()'
Python: 3.8.0 (default, Oct 28 2019, 16:14:01)
[GCC 8.3.0]
SymPy: 1.6.1
NumPy: 1.19.1
Matplotlib: 3.3.0
SciPy: 1.5.2
Lcapy: 0.63
```

**Comment by mph-** [comment]
I've generated a new release (V0.70) you can download from pip.  See also the updated docs.

**Comment by fakuivan** [comment]
I've installed 0.70 from pip and I can confirm the error has been solved

![image](https://user-images.githubusercontent.com/15100012/99327568-fe15b280-2858-11eb-8348-d466dc43a79c.png)

![image](https://user-images.githubusercontent.com/15100012/99327645-21406200-2859-11eb-9489-66a90a3349be.png)

Thank you for the help!
