### ISSUE TITLE
Cannot assign nodes which are not even added to the circuit.

### ISSUE THREAD

**Issue by lucatatas** [mph-/lcapy#47]
Hi,
I am getting the following error:

This error is showing up and it's listing nodes I have not added to my circuit.
![Screenshot 2021-02-03 212752](https://user-images.githubusercontent.com/62305393/106805595-301fff00-6667-11eb-8774-baddbd5df0cd.jpg)

Here is a list of which nodes I have added:
![Screenshot 2021-02-03 212812](https://user-images.githubusercontent.com/62305393/106805543-1c749880-6667-11eb-98a2-8b03bd24d32b.jpg)

I don't really know if this is just a simple bug of if I am using the library incorrectly.

Thanks in advance

**Comment by mph-** [comment]
Hello Luca

This is probably a bug and unfortunately this part of the code can be really tricky to debug.  Are you able to generate a simpler test case?

Michael

**Comment by mph-** [comment]
Could you please add the failing code but not as an image?

Thanks, Michael

**Comment by lucatatas** [comment]
Hi,I have just been reading this mail. I have found a workaround for the problem, but I can’t really share my code, because my code generates a random circuit so the problem is not really reproducible. Thanks anyway. RegardsLuca Tatas Von: mph-Gesendet: Dienstag, 9. Februar 2021 21:49An: mph-/lcapyCc: lucatatas; AuthorBetreff: Re: [mph-/lcapy] Cannot assign nodes which are not even added to the circuit. (#47) Could you please add the failing code but not as an image?Thanks, Michael—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mph-** [comment]
The master branch should no longer fail for this although the schematic may not have the desired symmetry.  This is a gnarly problem to solve since heuristics are required.  Instead, Lcapy now prints a message suggesting that a constraint is added between pairs of nodes (such as an open-circuit component) to enforce symmetry.

Michael.
