### ISSUE TITLE
zp2tf() issue

### ISSUE THREAD

**Issue by eriic1** [mph-/lcapy#5]
Hello,

I am having trouble using the zp2tf() function.  
It returns wih an error:  AttributeError: 'int' object has no attribute 'is_Mul'

If I follow along in the tutorial with the following:

from lcapy import *
H2 = zp2tf([], [0, -0.05]) 

I get the following output:
---

AttributeError                            Traceback (most recent call last)
<ipython-input-2-a2c69790f865> in <module>()
      1 from lcapy import *
----> 2 H2 = zp2tf([], [0, -0.05])

/usr/lib/python3.5/site-packages/lcapy/core.py in zp2tf(zeros, poles, K, var)
   1871     and from a constant gain"""
   1872 
-> 1873     return Hs(_zp2tf(zeros, poles, K, var))
   1874 
   1875 

/usr/lib/python3.5/site-packages/lcapy/core.py in _zp2tf(zeros, poles, K, var)
   1864         pp = [1 / (var - p) *\* poles[p] for p in poles]
   1865 
-> 1866     return uMul(K, *(zz + pp))
   1867 
   1868 

/usr/lib/python3.5/site-packages/sympy/core/mul.py in _unevaluated_Mul(*args)
     70     while args:
     71         a = args.pop()
---> 72         if a.is_Mul:
     73             c, nc = a.args_cnc()
     74             args.extend(c)

AttributeError: 'int' object has no attribute 'is_Mul'

This may just be caused by my setup but I had the same type error using Arch Linux with python 3.5 and on Ubuntu 16.04 using python 2.7.

I have been playing with the source code for a couple days to see if I could figure out the problem but have had no luck.  I wish I could help with this but I am pretty inexperienced with python code.

Thank you for creating this project and all you hard work.

Eric

**Comment by mph-** [comment]
Thanks for the bug report.  This is now fixed in 0.22.2.

Michael.
