### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by Veoooooo** [mph-/lcapy#51]
Hi
I want to execute this simple example but I couldn't do it 

code:

from lcapy import R, C, L
cct2= (R(1e6) + L(2e-3)) | C(3e-6)
cct2.draw()

and I get this error:
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\OneDrive - King Fahd University of Petroleum & Minerals (KFUPM)\\Electric Python\\tmppg8rlavz.log'

![image](https://user-images.githubusercontent.com/81289648/112273351-4f620280-8c8e-11eb-8269-d0bb1e84da05.png)
All the best, Alshehri.

**Comment by mph-** [comment]
Hello

Which version of lcapy are you running?

```
from lcapy import show_version
show_version()
```

**Comment by Veoooooo** [comment]
this is the version :
![image](https://user-images.githubusercontent.com/81289648/112370746-d0e97d00-8cee-11eb-9505-2340dd4f7234.png)

**Comment by Veoooooo** [comment]
this is when I try to run it on C drive:

![image](https://user-images.githubusercontent.com/81289648/112370864-f5ddf000-8cee-11eb-8015-9bf1211f3835.png)

**Comment by mph-** [comment]
Thanks for this.

I've pushed a patch to master; could you please check that it works for you?

**Comment by Veoooooo** [comment]
another error raised: 

![image](https://user-images.githubusercontent.com/81289648/112376797-f1690580-8cf5-11eb-9bd2-1ba72cf58b6a.png)

**Comment by mph-** [comment]
Did this use to work for V0.82?

**Comment by Veoooooo** [comment]
actually, I tried the new patch on another machine and it is working perfectly.
![image](https://user-images.githubusercontent.com/81289648/112381274-730f6200-8cfb-11eb-9ab6-b8e0960b7719.png)
Thanks a lot! 
All the best, Alshehri.

**Comment by Veoooooo** [comment]
> Did this use to work for V0.82?

no

**Comment by Veoooooo** [comment]
> another error raised:
> 
> ![image](https://user-images.githubusercontent.com/81289648/112376797-f1690580-8cf5-11eb-9bd2-1ba72cf58b6a.png)

I have found that there is a problem with the path of the files that lcapy produce 
and it is specific for the one drive path, if I use it some where else the lcapy library is working fine

**Comment by mph-** [comment]
Would you mind trying a patch I've pushed to master and then record the output from:

```
from lcapy import R
R(1).draw(debug=2)
```
The problem may be because I changed from saving temporary files in a temp directory and use the current working directory instead.  I know very little about Windows but I suspect that the current working directory may not be valid.

**Comment by Veoooooo** [comment]
yeah,  you are right this is working now thanks for your effort and I appreciate it.
![image](https://user-images.githubusercontent.com/81289648/112622414-1071af80-8e3c-11eb-9d17-2d4041a50b18.png)
