### ISSUE TITLE
Documentation's website is down

### ISSUE THREAD

**Issue by javovelez** [mph-/lcapy#55]

**Comment by psychemedia** [comment]
Still down... any chance of you also making it available via Github pages, even if not explicitly linked...?

**Comment by psychemedia** [comment]
I've never used readthedocs. What happens if you just enable Github pages from the repo settings and point it to main branch docs folder?

There are probably Github Actions that might be able to do the work too.

**Comment by mph-** [comment]
Unfortunately, the site has been taken offline until a security audit has been completed.  In the meantime I have been trying to migrate to readthedocs.org but have been having trouble trying to build the images.  Do you have any experience with this?  I may have to build the images myself and add them to the repository.

**Comment by mph-** [comment]
After much frustration, I've loaded the docs at https://lcapy.readthedocs.io/en/latest/  

Tomorrow, I'll try to get readthedocs to generate the images...

**Comment by javovelez** [comment]
Sorry, I'd love to help but I don't have any experience on the subject.

**Comment by psychemedia** [comment]
What's the issue re: generating the docs? Presumably you are managing to get the code to run?

I am using Jupyter Book for [this site](https://opencomputinglab.github.io/SubjectMatterNotebooks/) and it seems to work okay (I run Jupyter Book locally then copy the site files over. On to do list is the automation, but the environment is rather complex and I need to properly dockerise it.

**Comment by mph-** [comment]
I ended up having to include the images in the repo.  I could not find a way to run all the scripts on readthedocs and some take a long time to generate.
