### ISSUE TITLE
Warning messages although Circuit is drawing fine

### ISSUE THREAD

**Issue by lucatatas** [mph-/lcapy#57]
Hi, I have the following questino/issue: Sometims Lcapy prints some warning like the ones shown in the attached screenshot. Because these only seem to be warnings rather than actual errors, I don't really want them to be printed. So I'd like to know, where the print statement is located which prints these warning. Sadly I was not able to finde them on my own.
Thanks in advance!
![image](https://user-images.githubusercontent.com/62305393/128182769-2de1f561-e9d2-4d3a-9868-4b47cf130e53.png)

**Comment by mph-** [comment]
These are printed in lcapy/schemgraph.py; grep is your friend!

For your example, you are being warned about getting a wonky schematic.

I have pondered about using the python warnings subsystem so that specific warnings can be disabled but will need a rainy day to implement.

**Comment by lucatatas** [comment]
Hi, thank you for your answer, another question which came to my mind was the following: What are these nodes called "Wanon16" or "Wanon27" for example? I have not specifically added those so I was wondering why they are sometimes part of my circuit.

**Comment by mph-** [comment]
Each wire without an explicit name is given an anonymous name.  For example, W  1 2.
