### ISSUE TITLE
LoopAnalysis broken

### ISSUE THREAD

**Issue by Kyle-Gagner** [mph-/lcapy#58]
There is a bug in circuitgraph.py which breaks LoopAnalysis.

```
    def all_loops(self):

        # This adds forward and backward edges.
        DG = nx.DiGraph(self.G)
        cycles = list(nx.simple_cycles(DG))

        loops = []
        for cycle in cycles:
            if len(cycle) <= 2:
                continue
            cycle = sorted(cycle)
            if cycle not in loops:
                loops.append(cycle)        
        return loops
```

Sorting cycle means that the nodes in the cycle are now out of order. LoopAnalysis breaks because it looks for components between nodes which are not edges in the graph.

Here's a netlist for a broken case to reproduce:

```
C1 1 0
R1 2 0
L1 1 2
C2 3 0
R2 4 3
L2 1 4
```

**Comment by mph-** [comment]
Thanks for the test-case.  I have pushed a fixed for this.
