### ISSUE TITLE
"annotation" feature of circuitikz not recognised?

### ISSUE THREAD

**Issue by patzf** [mph-/lcapy#59]
The circuitikz manual (https://texdoc.org/serve/circuitikz/0) , chapter 5.1 Labels and Annotations tells that since v0.7 of circuitikz it is possible to specify not only a label to a component, but also an annotation.

I tried
`R1 1 2; right, size=1.5, l=R_1, a=$k$`

but it seems the "a" for annotation is ignored? Is it possible to get this feature?

Also (maybe I overlooked something), is there some documentation of the "extended"  netlist syntax of lcapy? It seems to be a mixture of SPICE style netlist and circuitikz features?

**Comment by mph-** [comment]
I have added this feature and pushed it to github. 

`R1 1 2; right, size=1.5, l=R_1, a^=k`

Yes, the syntax is a mixture of SPICE netlists with circuitikz attributes.   There is no complete summary; if you would like to compile one I would be happy to format it and add it to the rest of the docs.

Michael
