### ISSUE TITLE
Loop analysis shows `l_aplace` symbol

### ISSUE THREAD

**Issue by danieljfarrell** [mph-/lcapy#64]
I am running the example from the docs in latest version of lcapy.

Am I doing something stupid? Notice the appearance of a symbol called `l_aplace`.

```python
import lcapy
print(lcapy.__version__)  # '1.1'

cct = lcapy.Circuit("""
...V1 1 0; down
...R1 1 2; right
...L1 2 3; right
...R2 3 4; right
...L2 2 0_2; down
...C2 3 0_3; down
...R3 4 0_4; down
...W 0 0_2; right
...W 0_2 0_3; right
...W 0_3 0_4; right""")
cct.draw()
```
![image](https://user-images.githubusercontent.com/112847/145686625-269593cf-2fe2-415b-bcd3-72a3d07ee38e.png)

```python
cct.laplace().loop_analysis().matrix_equations(form="A y = b")
```
<img width="559" alt="Screenshot 2021-12-11 at 17 52 49" src="https://user-images.githubusercontent.com/112847/145686654-c9308ebd-6e24-4540-95dc-bcb9fc88d877.png">

**Comment by mph-** [comment]
I have pushed a fix for this.  Sorry for the delay; somehow I lost the email notification.

**Comment by danieljfarrell** [comment]
Great! Should I test it and close this issue? Or have you already tested it?

**Comment by mph-** [comment]
Yip, it seems to be fixed.
