### ISSUE TITLE
Running via Binderhub

### ISSUE THREAD

**Issue by psychemedia** [mph-/lcapy#7]
It would be useful if the repository was linked to [Binderhub](https://mybinder.org/) so that examples could be tried (and tested) interactively.

I think a minimal setup (though I haven't checked, may be:

### `apt.txt`

    texlive-xetex
    asymptote

There was a `tikz` dependency, I think, that `asymptote` handles.

### `requirements.txt`

    sympy
    matplotlib
    git+https://github.com/mph-/lcapy.git

**Comment by mph-** [comment]
This is an excellent idea.

I created [https://mybinder.org/v2/gh/mph-/lcapy/master)](https://mybinder.org/v2/gh/mph-/lcapy/master)

This exposed a bug that I fixed in 0.28.5.
