### ISSUE TITLE
Is nosim implemented for every type of component?

### ISSUE THREAD

**Issue by joaoantoniocardoso** [mph-/lcapy#70]
Hi, by reading the documentation I understood that the attribute `nosim` used in any component would disconnect it from the simulation, however, when I try to use it with MOSFETs or Diodes, the symbolic circuit solver just claims that the component is not implemented. `nosim` seems to be working for wires, so is it a bug? Am I missing something?

# Example

```python
from lcapy import Circuit

cct = Circuit(netlist="""
V1 1 0; down
R1 1 2; right
W 0 0_1; right
R2 2 0_1; down
W 2 3; right
RD1 3 _D1; down, invisible
VD1 _D1 4; down, invisible
D1 3 4; nosim, ignore, down
W 0_1 0_2; right
C1 4 0_2; down
""")
cct.draw(debug=True)
```
In this example code, the `cct.describe()` would work if we had D1 removed, but I am keeping it to see the error:

```python
circuitikz version 1.4.6 (2022[/02/04]())
width=2, height=3, dpi=150, cpt_size=1.50, node_spacing=2.00, scale=1.00
Nodes:
 1 @ (0,6), count=2, pin=False
 0 @ (0,0), count=2, pin=False
 2 @ (2,6), count=3, pin=False
 0_1 @ (2,0), count=3, pin=False
 3 @ (4,6), count=2, pin=False
 _D1 @ (4,4), count=2, pin=False
 4 @ (4,2), count=2, pin=False
 0_2 @ (4,0), count=2, pin=False
```
![output](https://user-images.githubusercontent.com/5920286/152784471-b4236b71-5af2-462d-99a1-bebb68b92346.png)

```Python
cct.describe()
```

```python
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
/tmp/ipykernel_18025/1923891856.py in <module>
     12 """)
     13 cct.draw(debug=True)
---> 14 cct.describe()

~/workspace_TCC/repo/code/env/lib/python3.8/site-packages/lcapy/netlistmixin.py in describe(self)
   2182 
   2183         groups = self.independent_source_groups(transform=not
-> 2184                                                 self.is_time_domain)
   2185 
   2186         if groups == {}:

~/workspace_TCC/repo/code/env/lib/python3.8/site-packages/lcapy/netlistmixin.py in is_time_domain(self)
   1954     def is_time_domain(self):
   1955         """Return True if can analyse in time domain."""
-> 1956         return self.analysis['time_domain']
   1957 
   1958     @property

~/workspace_TCC/repo/code/env/lib/python3.8/site-packages/lcapy/netlistmixin.py in analysis(self)
   2077 
   2078         if not hasattr(self, '_analysis'):
-> 2079             self._analysis = self.analyse()
   2080 
   2081         return self._analysis

~/workspace_TCC/repo/code/env/lib/python3.8/site-packages/lcapy/netlistmixin.py in analyse(self)
   2105             if elt.need_control_current:
   2106                 control_sources.append(elt.args[0])
-> 2107             if elt.has_ic is not None:
   2108                 if elt.has_ic:
   2109                     has_ic = True

~/workspace_TCC/repo/code/env/lib/python3.8/site-packages/lcapy/mnacpts.py in has_ic(self)
    490         """Return True if initial conditions are specified."""
    491 
--> 492         return self.cpt.has_ic
    493 
    494     @property

~/workspace_TCC/repo/code/env/lib/python3.8/site-packages/lcapy/mnacpts.py in cpt(self)
    722     @property
    723     def cpt(self):
--> 724          raise NotImplementedError('Invalid component for circuit analysis: %s' % self)
    725 
    726 

NotImplementedError: Invalid component for circuit analysis: D1 3 4; nosim, down
```

If this is not a bug, could we add it as a feature?

Thanks

**Comment by mph-** [comment]
Thanks for pointing this out.  Yes, it is a bug.  I added nosim recently to ignore a component from a simulation but never thought that someone would add it to a non-linear component that cannot be simulated.

I have pushed a fix for this.

**Comment by joaoantoniocardoso** [comment]
Great, I've just tested and it is working :cookie: thank you!

**Comment by YaoLiMuMu** [comment]
@joaoantoniocardoso the same code as you, but get different output picture
```python
from lcapy import Circuit

cct = Circuit(netlist="""
V1 1 0; down
R1 1 2; right
W 0 0_1; right
R2 2 0_1; down
W 2 3; right
RD1 3 _D1; down, invisible
VD1 _D1 4; down, invisible
D1 3 4; nosim, ignore, down
W 0_1 0_2; right
C1 4 0_2; down
""")
```
cct.draw(debug=True)
![appendix_c1111](https://github.com/mph-/lcapy/assets/32826811/36fac3ed-639e-487d-8e68-e649eccb78d9)

**Comment by joaoantoniocardoso** [comment]
> @joaoantoniocardoso the same code as you, but get different output picture
> 
> ```python
> from lcapy import Circuit
> 
> cct = Circuit(netlist="""
> V1 1 0; down
> R1 1 2; right
> W 0 0_1; right
> R2 2 0_1; down
> W 2 3; right
> RD1 3 _D1; down, invisible
> VD1 _D1 4; down, invisible
> D1 3 4; nosim, ignore, down
> W 0_1 0_2; right
> C1 4 0_2; down
> """)
> cct.draw(debug=True)
> ```
> 
> ![appendix_c1111](https://private-user-images.githubusercontent.com/32826811/318409062-36fac3ed-639e-487d-8e68-e649eccb78d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NzY2NTMsIm5iZiI6MTcxMTk3NjM1MywicGF0aCI6Ii8zMjgyNjgxMS8zMTg0MDkwNjItMzZmYWMzZWQtNjM5ZS00ODdkLThlNjgtZTY0OWVjY2I3OGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEyNTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNzJiN2I2ZWJkY2MxOWQyODFlM2FkMjNjNDRkNWNiNTdhOTllZDRmNGE4ZWUxZDZlODg2ZWY4Yjk4NGJjODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xPEL_1bvPnydaTYSZBn5kiLUxWUgNtWiUxRKxRxmWZI)

This must be a regression. Please, can you open a new Issue linking this one?
