### ISSUE TITLE
lcapy expressions are failing to interpret latex symbols.

### ISSUE THREAD

**Issue by joaoantoniocardoso** [mph-/lcapy#71]
Hi, I am using lcapy together with sympy, but I am facing something weird when trying to use expressions with latex symbols:

``` python
import sympy as sym
sym.init_printing()
from lcapy import TimeDomainExpression

t = TimeDomainExpression('t')

# This works:
hi_o = sym.Function('\hat{i_o}', real=True)(t)
TimeDomainExpression(hi_o)

# This fails, it is showing "_hato"
ho = sym.Function('\hat{o}', real=True)(t)
TimeDomainExpression(ho)

# Workarround - not ideal, but appending an underscore "_" seems to help:
ho = sym.Function('\hat{o}_', real=True)(t)
TimeDomainExpression(ho)

# Note that simpler latex like '\Delta' also fails.

```

edit:
I'm using it in a jupyter notebook, and the `.name` of the expressions seems right, I think it should be something with the printer.

edit2:
Adding an image to help us to visualize the issue:

![image](https://user-images.githubusercontent.com/5920286/153736345-bf4983ed-4da3-48ee-ae08-def4e0dba03c.png)

Thanks

**Comment by mph-** [comment]
Thanks for this.  I'm about to push a patch to fix `canonical_name` in printing.py

Your example also raises another Lcapy problem, `lcapy.symbol('\hat{x}')` fails.

Note, where possible you should use the Lcapy functions and classes instead of the SymPy ones due to all the chicanery required to make things work.

**Comment by joaoantoniocardoso** [comment]
> Thanks for this. I'm about to push a patch to fix `canonical_name` in printing.py
> 
> Your example also raises another Lcapy problem, `lcapy.symbol('\hat{x}')` fails.
> 
> Note, where possible you should use the Lcapy functions and classes instead of the SymPy ones due to all the chicanery required to make things work.

Nice! Your [commit](https://github.com/mph-/lcapy/commit/88fc0089c02f8ab690d4eb0b7a41afab3a50e970) fixed the printing issue!

Specifically about the `lcapy.symbol('\hat{x}')`, that's why I was first creating the symbol in sympy: `lcapy.symbol(sym.Symbol('\hat{x}'))` for constants, and `TimeDomainExpression(sym.Symbol('\hat{x}'))` for currents and voltages, but I am not particularly knowledge about any side effects. May I ask you a suggestion if is this the best approach?

And thanks for your fast reply, your work is fantastic!

**Comment by mph-** [comment]
I have pushed a fix to allow arbitrary symbol names if created by the `symbol` or `symbols` function.

**Comment by joaoantoniocardoso** [comment]
Perfect, I tested and this really helps. Thank you so much for your work!
