### ISSUE TITLE
Strange behavior when using subs()

### ISSUE THREAD

**Issue by joaoantoniocardoso** [mph-/lcapy#74]
Hi there! So, I am facing a strange behavior when using subs on the StateSpace before using it on the Circuit and I have no idea what it could be. I accidentally discovered a workaround:

```Python
import lcapy as lca

cct_on = lca.Circuit(netlist="""P1 i 0; down, v={v_{i}(t)}
V1 i 0 {vi(t)}; down, i={i_{i}(t)}, v={v_{i}(t)}, invisible
L1 i M; right, i={i_{li}(t)}, v={v_{li}(t)}
W  0    0_1; right
C1 M D; right, i={i_{cc}(t)}, v={v_{cc}(t)}
W  M 0_1; down, i={i_{M}}
P3 D 0_2; down, v={v_{D}}
W  0_1 0_2; right
P2 nP21 out; up, v={v_{o}(t)}
I1 nP21 out {io(t)}; up, invisible
W  o out; right, i={i_{o}(t)}
L2 D o; right, i={i_{lo}(t)}, v={v_{lo}(t)}
C2 nC22 o; up, i={i_{co}(t)}, v={v_{co}(t)}
W  nC22 nP21; right
W  0_2  nC22; right"""
)
ss_on = cct_on.ss

display(ss_on.A)
display(ss_on.subs({'C1': 2}).A)

print("---")

C1 = ss_on.A[9].args[0]
print(C1, C1.name, type(C1), C1.name == 'C1')
display(ss_on.subs({C1: 3}).A)

print("---")

# cct_on.subs({})

print("---")

# after calling this, dictionary using 
# the component name starts to work:
display(ss_on.A)
display(ss_on.subs({'C1': 2}).A)
```
The Output without the Circuit.subs:
![image](https://user-images.githubusercontent.com/5920286/153782345-ba63d7b6-8cb2-4d9c-b79a-1711633ab925.png)

The Output with the Circuit.subs:
![image](https://user-images.githubusercontent.com/5920286/153782312-f1f14ae9-eda8-4a07-8060-e0482f199030.png)

Thanks again!

**Comment by mph-** [comment]
Ah, this is a gnarly one.  It arises from a bug where some symbols in an expression are not being added to Lcapy's symbol registry.  This registry is required to overcome the problem with SymPy where different symbols can share the same name.    I'll look for a fix tomorrow.
