### ISSUE TITLE
Arrow of voltage drop in european style not correctly displayed 

### ISSUE THREAD

**Issue by lucatatas** [mph-/lcapy#82]
Hi, 

I have a general issue considering the direction of the voltage drop.
Imagine I have a basic circuit like this:
```
c = Circuit("""
R a c 1; down=0.7, scale = 0.5, v=V_r
W a b; right=0.7, scale = 0.5
W c d; right=0.7, scale = 0.5
P b d; down=0.7, v=V_o, scale = 0.5
""")
```

which looks like this when I don't use the european style:
![grafik](https://user-images.githubusercontent.com/62305393/173332870-a137731c-bcea-450d-9fd2-7903856537d3.png)

But looks like this when I use the european style to draw the circuit:
![grafik](https://user-images.githubusercontent.com/62305393/173332949-c5e26834-5b01-4b3c-9ce9-f94f985bdb73.png)

The arrows of the voltage drops are clearly flipped.
I am also referring to issue #75

Thanks in advance!

**Comment by mph-** [comment]
There is a `voltage_dir` option that can be 'RP' for rising potential (default) and 'EF' for electric field. 

For example, `cct.draw(style='european', voltage_dir='EF')`

See the Circuitikz docs https://www.ctan.org/pkg/circuitikz/doc
