### ISSUE TITLE
Nodal analysis of Laplace model does not include initial conditions

### ISSUE THREAD

**Issue by scottprahl** [mph-/lcapy#84]
Consider the following circuit with initial conditions

```
import lcapy
cct=lcapy.Circuit("""
C 1 0 1 15; down
L 1 2 1 5; right
R1 2 0 3; down
R2 2 3 15; right
V 3 0 15; down
;autoground=True,label_ids=False
""")
cct.s_model().draw()
```

which shows the correct circuit with voltage sources to account for the initial conditions.

![image](https://user-images.githubusercontent.com/1901078/173640133-f36e2ab3-50c9-4cfd-a997-2b648936a19e.png)

Unfortunately `nodal_analysis()` fails to include these voltage sources

```
n = cct.laplace().nodal_analysis()
n.nodal_equations()
```

<img width="685" alt="image" src="https://user-images.githubusercontent.com/1901078/173640644-4cb05147-6db7-4294-a0be-413598ed71e3.png">

`lcapy` *does include* the initial conditions when analyzing the circuit (i.e., `cct[2].v` gives the correct answer).  So maybe this is just overlooked in `nodal_analysis()`?

**Comment by mph-** [comment]
Thanks for the example.  Yes, this was overlooked.  The same problem applies for loop analysis.  It should be straightforward to fix.   Stay tuned once I've had a sleep...

**Comment by mph-** [comment]
I think I have fixed this but will need to write some unit tests.

**Comment by scottprahl** [comment]
Things aren't quite right yet.  Using version 7ca1151e gives

![image](https://user-images.githubusercontent.com/1901078/174195839-b1a71043-5a6e-42d2-8738-cb510ae4bc56.png)

The correct equations should be

```
v1, v2, s, t = sympy.symbols('v_1 v_2 s t')
eq1 = (v1-15/s)/(1/s) + (v1-(v2-5))/s
eq2 = -(v1-(v2-5))/s + (v2-15/s)/15 + v2/3
sympy.solve([eq1,eq2], (v1,v2))
```

(the inverse Laplace transform gives the same solutions as `cct[1].v` and `cct[2].v`)

It looks like the initial condition for the capacitor voltage is off by $s^2$

**Comment by mph-** [comment]
Sorry, in my haste I multiplied by s rather than dividing by s.

**Comment by scottprahl** [comment]
It works now!  Thanks for the fix.
