### ISSUE TITLE
Add mesh_analysis() method to Circuit() object

### ISSUE THREAD

**Issue by scottprahl** [mph-/lcapy#87]
This does nodal analysis

```
n = cct.nodal_analysis()
eqns = n.nodal_equations()
```

Currently mesh analysis is done with

```
l = cct.loop_analysis()
eqns = l.mesh_equations()
```

I'd like to see `mesh_analysis()` added as a synonym/alias for `loop_analysis()` to match the parallel structure of the nodal methods:

```
m = cct.mesh_analysis()
eqns = m.mesh_equations()
```

This also allows for easier discovery of the mesh method through `dir(cct)` or `help(cct)`.

**Comment by mph-** [comment]
Done!   This was a good idea.  In my mind mesh analysis is a special case of loop analysis.  Since I have only implemented mesh analysis, I created an alias.

**Comment by scottprahl** [comment]
This works!  Thanks
