### ISSUE TITLE
Removing undefined symbols from TimeDomainVoltage object

### ISSUE THREAD

**Issue by lucatatas** [mph-/lcapy#88]
Hi, 
I am trying to evaluate the result of a transfer function at specific timepoints to plot it.
The result is of object type ```<class 'lcapy.expressionclasses.TimeDomainVoltage'>```.
I know, that I can evaluate this expression at the desired timesteps using ```.evaluate()```.

My problem is that I use non defined variables in my expression to display a general transfer function. 
Now, when I want to evaluate the expression at the desired timesteps I need to replace these non defined variables or it will raise a ValueError:
![grafik](https://user-images.githubusercontent.com/62305393/182594075-3e4481d1-8351-4e6d-8a58-8550b094d71b.png)

My question is: 
How can I modify the TimeDomainVoltage object in a way I can still call ```.evaluate()``` on it?
Sure, I could easily convert the TimeDomainVoltage object to a string and then call ```.replace()``` to replace my non defined variables, but then I would not be able to call ```.evaluate()``` on it, because the object was obviously converted to a string beforehand.

I hope you understand what my problem is and thanks in advance!

**Comment by mph-** [comment]
You can use the subs method, for example, something like  `H.subs({'R0': 100, 'C0':1e-6})`.  This will return a new Lcapy expression.

**Comment by lucatatas** [comment]
Thanks!
