### ISSUE TITLE
Calculate response to sin function

### ISSUE THREAD

**Issue by p123123** [mph-/lcapy#9]
When running the following circuit
```
from lcapy import Circuit, s, t, f, R, L, C
cct = Circuit()
cct.add('V1 1 0 {3*sin(t)}; down')
cct.add('R1 1 2 1; right=1.5')
cct.add('L1 2 3 0.25; down=1.5')
cct.add('W1 0 3; right')
cct.draw()
ax = cct.R1.i.plot() # current
ax = cct.R1.v.plot() # voltage     
```
the plots show a zero current and voltage. I would expect a sine function (with certain amplitude and phase). When replacing `3*sin(t)` with `3*u(t)` the result is as expected.

**Comment by mph-** [comment]
Thanks for letting me know about this.  It was due to a bug in AC analysis when the frequency is known. It is fixed in 0.28.3.

Michael.
