### ISSUE TITLE
Drawing a choke

### ISSUE THREAD

**Issue by odkken** [mph-/lcapy#93]
Hi, I'm trying to insert a choke inductor into a circuit for the sole purpose of drawing:
![image](https://user-images.githubusercontent.com/3037938/199260394-938d3341-a647-4246-9411-ade3663c0683.png)

I'm able to render that using
```
cct = Circuit("""
;;\draw (0,0) to[cute choke, twolineschoke] ++(2,0);
""")
cct.draw()
```

but am hoping there's a way to get this symbol using normal lcapy circuit symbols:

```
cct = Circuit("""
A1 0; l=\mathrm{VSW\_ABC}, anchor=east
L6 0 1 .00000033; #<-- make this a choke
;label_nodes=false""")
cct.draw()
```
![image](https://user-images.githubusercontent.com/3037938/199262583-fca45de7-a709-4dd6-ae6a-40f024f502a0.png)

Is there a semi-painless way to substitute out symbols like this, or change the style on individual components?  I tried playing with the example of ``` ;; \ctikzset{inductor=cute}```
which works for switching between the american/cute styles, but couldn't change to choke versions.

**Comment by mph-** [comment]
I have just pushed a patch to support this.  This now supports the following:

    L1 1 2; right, kind=choke
    L2 2 3; right, kind=twolineschoke

**Comment by odkken** [comment]
Amazin!  Thanks.
