### ISSUE TITLE
Simple circuit great mistake

### ISSUE THREAD

**Issue by ees4all** [mph-/lcapy#97]
I have tested the MeshAnalysis
i got this mistake. you can see with one resistor does not work, instead with 2 resistor works. As Lcapy has great potential for education. This issue should be analysed. What about students get such wrong answer?

Thanks for your effort, it is great!
Happy new years eve (31.12.2022 9:15pm ...working :-) )
[dc Analysis.zip](https://github.com/mph-/lcapy/files/10327939/dc.Analysis.zip)

**Comment by mph-** [comment]
Thanks for the bug report.  It should be fixed now.

**Comment by mph-** [comment]
BTW, I have a pushed a patch to fix formatting of component names with an underscore.
